export const germanCities = [
  'Berlin, Germany',
  'Hamburg, Germany',
  'München (Munich), Germany',
  'Köln (Cologne), Germany',
  'Frankfurt am Main, Germany',
  'Stuttgart, Germany',
  'Düsseldorf, Germany',
  'Dortmund, Germany',
  'Essen, Germany',
  'Leipzig, Germany',
  'Bremen, Germany',
  'Dresden, Germany',
  'Hannover, Germany',
  'Nürnberg (Nuremberg), Germany',
  'Duisburg, Germany',
  'Bochum, Germany',
  'Wuppertal, Germany',
  'Bielefeld, Germany',
  'Bonn, Germany',
  'Münster, Germany',
  'Karlsruhe, Germany',
  'Mannheim, Germany',
  'Augsburg, Germany',
  'Wiesbaden, Germany',
  'Gelsenkirchen, Germany',
  'Mönchengladbach, Germany',
  'Braunschweig, Germany',
  'Chemnitz, Germany',
  'Kiel, Germany',
  'Aachen, Germany',
  'Halle (Saale), Germany',
  'Magdeburg, Germany',
  'Freiburg im Breisgau, Germany',
  'Krefeld, Germany',
  'Lübeck, Germany',
  'Oberhausen, Germany',
  'Erfurt, Germany',
  'Mainz, Germany',
  'Rostock, Germany',
  'Kassel, Germany',
  'Hagen, Germany',
  'Hamm, Germany',
  'Saarbrücken, Germany',
  'Mülheim an der Ruhr, Germany',
  'Potsdam, Germany',
  'Ludwigshafen am Rhein, Germany',
  'Oldenburg, Germany',
  'Leverkusen, Germany',
  'Osnabrück, Germany',
  'Solingen, Germany',
  'Heidelberg, Germany',
  'Herne, Germany',
  'Neuss, Germany',
  'Darmstadt, Germany',
  'Paderborn, Germany',
  'Regensburg, Germany',
  'Ingolstadt, Germany',
  'Würzburg, Germany',
  'Fürth, Germany',
  'Wolfsburg, Germany',
  'Offenbach am Main, Germany',
  'Ulm, Germany',
  'Heilbronn, Germany',
  'Pforzheim, Germany',
  'Göttingen, Germany',
  'Bottrop, Germany',
  'Trier, Germany',
  'Recklinghausen, Germany',
  'Reutlingen, Germany',
  'Bremerhaven, Germany',
  'Koblenz, Germany',
  'Bergisch Gladbach, Germany',
  'Jena, Germany',
  'Remscheid, Germany',
  'Erlangen, Germany',
  'Moers, Germany',
  'Siegen, Germany',
  'Hildesheim, Germany',
  'Salzgitter, Germany',
  // 50 neue Städte
  'Cottbus, Germany',
  'Kaiserslautern, Germany',
  'Gütersloh, Germany',
  'Schwerin, Germany',
  'Witten, Germany',
  'Hanau, Germany',
  'Ludwigsburg, Germany',
  'Esslingen am Neckar, Germany',
  'Oberursel, Germany',
  'Ratingen, Germany',
  'Lünen, Germany',
  'Marl, Germany',
  'Velbert, Germany',
  'Minden, Germany',
  'Dessau-Roßlau, Germany',
  'Villingen-Schwenningen, Germany',
  'Rheine, Germany',
  'Troisdorf, Germany',
  'Detmold, Germany',
  'Bayreuth, Germany',
  'Norderstedt, Germany',
  'Arnsberg, Germany',
  'Landshut, Germany',
  'Aschaffenburg, Germany',
  'Dinslaken, Germany',
  'Lüdenscheid, Germany',
  'Castrop-Rauxel, Germany',
  'Gladbeck, Germany',
  'Bocholt, Germany',
  'Brandenburg an der Havel, Germany',
  'Celle, Germany',
  'Lörrach, Germany',
  'Düren, Germany',
  'Bamberg, Germany',
  'Plauen, Germany',
  'Neu-Ulm, Germany',
  'Weimar, Germany',
  'Aschersleben, Germany',
  'Aalen, Germany',
  'Goslar, Germany',
  'Fulda, Germany',
  'Herford, Germany',
  'Grevenbroich, Germany',
  'Kerpen, Germany',
  'Dormagen, Germany',
  'Bergheim, Germany',
  'Landau in der Pfalz, Germany',
  'Schwäbisch Gmünd, Germany',
  'Friedrichshafen, Germany',
  'Neubrandenburg, Germany',
  'Werl, Germany',
];

export const creatorOneEvents = [
  {
    name: 'High-Energy Marathon 2024',
    category: 'Sport',
    description: 'Join us for a thrilling marathon event showcasing endurance and speed.',
    date: '2024-02-12T09:00:00',
    location: 'Central Park',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Essen Kayak Race',
    category: 'Sport',
    description: 'Paddle swiftly in the Essen kayak challenge.',
    date: '2024-02-11T09:30:00',
    location: 'Essen, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Düsseldorf Skateboarding Expo',
    category: 'Sport',
    description: 'Show off your skateboarding skills in Düsseldorf.',
    date: '2024-02-17T13:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Hamburg Beach Volleyball',
    category: 'Sport',
    description: 'Spike and serve at the Hamburg beach volleyball competition.',
    date: '2024-02-23T16:45:00',
    location: 'Hamburg, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Werl Photography Exhibit',
    category: 'Art',
    description: 'Discover the beauty of Werl through local photography.',
    date: '2024-02-14T19:00:00',
    location: 'Werl, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Essen Jazz Evening',
    category: 'Music',
    description: 'Smooth jazz and relaxing vibes in Essen.',
    date: '2024-02-20T17:30:00',
    location: 'Essen, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Düsseldorf Hardstyle Festival',
    category: 'Music',
    description: 'Beat out at the annual Werl rock music festival.',
    date: '2024-02-22T19:45:00',
    location: 'Düsseldorf, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Düsseldorf Jazz Soiree',
    category: 'Music',
    description: 'Experience an evening of smooth jazz and soulful melodies in Düsseldorf.',
    date: '2024-02-10T20:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Düsseldorf eSports Championship',
    category: 'Gaming',
    description: 'Compete in the ultimate eSports event in Düsseldorf.',
    date: '2024-02-13T20:30:00',
    location: 'Düsseldorf, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Hamburg Gaming Hackathon',
    category: 'Gaming',
    description: 'Join the gaming community for a creative hackathon in Hamburg.',
    date: '2024-02-18T18:00:00',
    location: 'Hamburg, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Werl Mobile Gaming Gathering',
    category: 'Gaming',
    description: 'Join us for a fun-filled day of mobile gaming in Werl.',
    date: '2024-02-24T14:30:00',
    location: 'Werl, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Hamburg Vegan Feast',
    category: 'Food',
    description: 'Explore a variety of delicious vegan dishes at our Hamburg Vegan Feast.',
    date: '2024-02-11T18:00:00',
    location: 'Hamburg, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Werl BBQ Challenge',
    category: 'Food',
    description: 'Join us for a sizzling BBQ challenge in Werl.',
    date: '2024-02-18T17:00:00',
    location: 'Werl, Germany',
    creator: 'p13p2506b4kjd7d',
  },
  {
    name: 'Essen Farm-to-Table Dinner',
    category: 'Food',
    description: 'Experience the freshest flavors at our farm-to-table dinner in Essen.',
    date: '2024-02-24T18:30:00',
    location: 'Essen, Germany',
    creator: 'p13p2506b4kjd7d',
  },
];

export const creatorTwoEvents = [
  {
    name: 'Ultimate Frisbee Championship',
    category: 'Sport',
    description: 'Compete or watch as teams battle for the Ultimate Frisbee title.',
    date: '2024-02-18T14:00:00',
    location: 'Beachside Arena',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Hamburg Sushi Workshop',
    category: 'Food',
    description: 'Learn the art of sushi making from expert chefs in Hamburg.',
    date: '2024-02-20T19:00:00',
    location: 'Hamburg, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Werl Soccer Tournament',
    category: 'Sport',
    description: 'Teams compete for the championship title in Werl.',
    date: '2024-02-13T10:45:00',
    location: 'Werl, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Essen Martial Arts Workshop',
    category: 'Sport',
    description: 'Learn from the masters at the Essen martial arts workshop.',
    date: '2024-02-19T14:15:00',
    location: 'Essen, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Düsseldorf Art Night',
    category: 'Art',
    description: 'A night of art exhibitions and performances in Düsseldorf.',
    date: '2024-02-10T17:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Hamburg Graffiti Tour',
    category: 'Art',
    description: 'Explore Hamburg’s vibrant street art scene.',
    date: '2024-02-16T20:15:00',
    location: 'Hamburg, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Werl Rock Festival',
    category: 'Music',
    description: 'Rock out at the annual Werl rock music festival.',
    date: '2024-02-22T18:45:00',
    location: 'Werl, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Düsseldorf Techno Festival',
    category: 'Music',
    description: 'Techno out at the annual Werl rock music festival.',
    date: '2024-02-22T18:45:00',
    location: 'Düsseldorf, Germany',
    creator: 'ea4iznf4xzf7bog',
  },

  {
    name: 'Essen Classical Music Night',
    category: 'Music',
    description: 'Delight in the timeless beauty of classical music under the stars in Essen.',
    date: '2024-02-15T18:30:00',
    location: 'Essen, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Düsseldorf Board Game Night',
    category: 'Gaming',
    description: 'Enjoy a night of classic and modern board games in Düsseldorf.',
    date: '2024-02-20T19:30:00',
    location: 'Düsseldorf, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Essen Virtual Reality Expo',
    category: 'Gaming',
    description: 'Dive into the latest VR technologies and games in Essen.',
    date: '2024-02-14T15:00:00',
    location: 'Essen, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Hamburg Retro Gaming Evening',
    category: 'Gaming',
    description: 'Relive the nostalgia with classic games at our retro gaming evening in Hamburg.',
    date: '2024-02-10T20:00:00',
    location: 'Hamburg, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Essen Wine Tasting',
    category: 'Food',
    description: 'Sample fine wines from around the world in Essen.',
    date: '2024-02-15T18:00:00',
    location: 'Essen, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Düsseldorf International Food Market',
    category: 'Food',
    description: 'Taste the world at the Düsseldorf International Food Market.',
    date: '2024-02-13T12:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
  {
    name: 'Werl Wine and Cheese Night',
    category: 'Food',
    description: 'Enjoy an exquisite selection of wines and cheeses in Werl.',
    date: '2024-02-25T20:00:00',
    location: 'Werl, Germany',
    creator: 'ea4iznf4xzf7bog',
  },
];

export const creatorThirdEvents = [
  {
    name: 'Düsseldorf City Run',
    category: 'Sport',
    description: 'A scenic run through the historic streets of Düsseldorf.',
    date: '2024-02-10T08:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'yravb0dwvhao0gb',
  },
  {
    name: 'Hamburg Triathlon',
    category: 'Sport',
    description: 'Test your endurance in the ultimate Hamburg triathlon.',
    date: '2024-02-15T11:00:00',
    location: 'Hamburg, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Werl Cycling Day',
    category: 'Sport',
    description: 'Join the community for a cycling day around Werl.',
    date: '2024-02-21T15:30:00',
    location: 'Werl, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Essen Sculpture Walk',
    category: 'Art',
    description: 'A guided walk through Essen’s most famous sculptures.',
    date: '2024-02-12T18:30:00',
    location: 'Essen, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Düsseldorf Interactive Art Festival',
    category: 'Art',
    description: 'Engage with interactive art installations in Düsseldorf.',
    date: '2024-02-18T21:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'yravb0dwvhao0gb',
  },
  {
    name: 'Essen Interactive Art Festival',
    category: 'Art',
    description: 'Engage with interactive art installations in Düsseldorf.',
    date: '2024-02-18T21:00:00',
    location: 'Essen, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Hamburg Hardstyle Festival',
    category: 'Music',
    description: 'Beat out at the annual Hamburg rock music festival.',
    date: '2024-02-22T19:45:00',
    location: 'Hamburg, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Werl Pop Concert',
    category: 'Music',
    description: 'Sing along to your favorite pop hits at the vibrant Werl pop concert.',
    date: '2024-02-18T19:00:00',
    location: 'Werl, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Hamburg Game Developer Meetup',
    category: 'Gaming',
    description: 'Connect with game developers and gamers in Hamburg.',
    date: '2024-02-11T19:00:00',
    location: 'Hamburg, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Werl Indie Game Showcase',
    category: 'Gaming',
    description: 'Discover unique indie games and meet the creators in Werl.',
    date: '2024-02-16T16:30:00',
    location: 'Werl, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Essen Console Gaming Tournament',
    category: 'Gaming',
    description: 'Compete against the best in console gaming in Essen.',
    date: '2024-02-22T17:00:00',
    location: 'Essen, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Düsseldorf Game Development Workshop',
    category: 'Gaming',
    description: 'Learn game development from industry experts in Düsseldorf.',
    date: '2024-02-12T18:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Werl Culinary Night',
    category: 'Food',
    description: 'A night of culinary delights and gourmet dishes in Werl.',
    date: '2024-02-17T19:15:00',
    location: 'Werl, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Essen Chocolate Festival',
    category: 'Food',
    description:
      'Indulge in the finest chocolates from around the globe at the Essen Chocolate Festival.',
    date: '2024-02-15T14:30:00',
    location: 'Essen, Germany',
    creator: 'yravb0dwvhao0gb',
  },

  {
    name: 'Düsseldorf Craft Beer Tasting',
    category: 'Food',
    description: 'Discover unique craft beers at our tasting event in Düsseldorf.',
    date: '2024-02-22T16:00:00',
    location: 'Düsseldorf, Germany',
    creator: 'yravb0dwvhao0gb',
  },
];
