export const germanCities = [
  'Berlin, Germany',
  'Hamburg, Germany',
  'München (Munich), Germany',
  'Köln (Cologne), Germany',
  'Frankfurt am Main, Germany',
  'Stuttgart, Germany',
  'Düsseldorf, Germany',
  'Dortmund, Germany',
  'Essen, Germany',
  'Leipzig, Germany',
  'Bremen, Germany',
  'Dresden, Germany',
  'Hannover, Germany',
  'Nürnberg (Nuremberg), Germany',
  'Duisburg, Germany',
  'Bochum, Germany',
  'Wuppertal, Germany',
  'Bielefeld, Germany',
  'Bonn, Germany',
  'Münster, Germany',
  'Karlsruhe, Germany',
  'Mannheim, Germany',
  'Augsburg, Germany',
  'Wiesbaden, Germany',
  'Gelsenkirchen, Germany',
  'Mönchengladbach, Germany',
  'Braunschweig, Germany',
  'Chemnitz, Germany',
  'Kiel, Germany',
  'Aachen, Germany',
  'Halle (Saale), Germany',
  'Magdeburg, Germany',
  'Freiburg im Breisgau, Germany',
  'Krefeld, Germany',
  'Lübeck, Germany',
  'Oberhausen, Germany',
  'Erfurt, Germany',
  'Mainz, Germany',
  'Rostock, Germany',
  'Kassel, Germany',
  'Hagen, Germany',
  'Hamm, Germany',
  'Saarbrücken, Germany',
  'Mülheim an der Ruhr, Germany',
  'Potsdam, Germany',
  'Ludwigshafen am Rhein, Germany',
  'Oldenburg, Germany',
  'Leverkusen, Germany',
  'Osnabrück, Germany',
  'Solingen, Germany',
  'Heidelberg, Germany',
  'Herne, Germany',
  'Neuss, Germany',
  'Darmstadt, Germany',
  'Paderborn, Germany',
  'Regensburg, Germany',
  'Ingolstadt, Germany',
  'Würzburg, Germany',
  'Fürth, Germany',
  'Wolfsburg, Germany',
  'Offenbach am Main, Germany',
  'Ulm, Germany',
  'Heilbronn, Germany',
  'Pforzheim, Germany',
  'Göttingen, Germany',
  'Bottrop, Germany',
  'Trier, Germany',
  'Recklinghausen, Germany',
  'Reutlingen, Germany',
  'Bremerhaven, Germany',
  'Koblenz, Germany',
  'Bergisch Gladbach, Germany',
  'Jena, Germany',
  'Remscheid, Germany',
  'Erlangen, Germany',
  'Moers, Germany',
  'Siegen, Germany',
  'Hildesheim, Germany',
  'Salzgitter, Germany',
  // 50 neue Städte
  'Cottbus, Germany',
  'Kaiserslautern, Germany',
  'Gütersloh, Germany',
  'Schwerin, Germany',
  'Witten, Germany',
  'Hanau, Germany',
  'Ludwigsburg, Germany',
  'Esslingen am Neckar, Germany',
  'Oberursel, Germany',
  'Ratingen, Germany',
  'Lünen, Germany',
  'Marl, Germany',
  'Velbert, Germany',
  'Minden, Germany',
  'Dessau-Roßlau, Germany',
  'Villingen-Schwenningen, Germany',
  'Rheine, Germany',
  'Troisdorf, Germany',
  'Detmold, Germany',
  'Bayreuth, Germany',
  'Norderstedt, Germany',
  'Arnsberg, Germany',
  'Landshut, Germany',
  'Aschaffenburg, Germany',
  'Dinslaken, Germany',
  'Lüdenscheid, Germany',
  'Castrop-Rauxel, Germany',
  'Gladbeck, Germany',
  'Bocholt, Germany',
  'Brandenburg an der Havel, Germany',
  'Celle, Germany',
  'Lörrach, Germany',
  'Düren, Germany',
  'Bamberg, Germany',
  'Plauen, Germany',
  'Neu-Ulm, Germany',
  'Weimar, Germany',
  'Aschersleben, Germany',
  'Aalen, Germany',
  'Goslar, Germany',
  'Fulda, Germany',
  'Herford, Germany',
  'Grevenbroich, Germany',
  'Kerpen, Germany',
  'Dormagen, Germany',
  'Bergheim, Germany',
  'Landau in der Pfalz, Germany',
  'Schwäbisch Gmünd, Germany',
  'Friedrichshafen, Germany',
  'Neubrandenburg, Germany',
];
